name: Run Git bot
on:
  issue_comment:
    types:
      - created

env:
  TF_CLOUD_ORGANIZATION: "Test-Terraform-Demos"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "demo-github-actions"
  CONFIG_DIRECTORY: "./"

jobs:
  git-bot:
    if: ${{ github.event.comment.body == '/bot destroy' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Terraform init
        id: terraform init
        run: terraform init
      
      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: plan-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}
          speculative: true

      - name: Destroy Infrastructure
        run: terraform destroy -auto-approve 
 
